### PR TITLE
Remove role "Wants to help" when onboarded

### PR DESCRIPTION
**Pull request by Wituareard**
Requires an additional field in Airtable named `Wants to help`

### CODE REVIEW

**Comment by Maximophone** [comment]
Have you tested the change ?

**Comment by Wituareard** [comment]
Yes

**Comment by Wituareard** [comment]
@Maximophone The Airtable field seems to be missing

**Comment by Maximophone** [comment]
I've added a field "Wants to help" in the Onboarding Events table in both devel and prod. 
How did you test the changes if the field wasn't there?

**Comment by Wituareard** [comment]
I tested with my own copy of the base because otherwise I wouldn't be able to generate a key that can edit it

**Pull request merged**
